spring:

  config:
    import: jwt.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/Brightdemy
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 200GB
      max-request-size: 215GB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8090

